### ISSUE TITLE
How to share configuration of adapter with multiple languages?

### ISSUE THREAD

**Issue by chewbakartik** [jayp0521/mason-nvim-dap.nvim#12]
First off thanks for this plugin, I'm feeling kind of overwhelmed with dap setup and configuration, and am finding these sorts of things helpful.

Second piece is probably me just being pretty dense, but I'm trying to figure out how to use this plugin to configure the rust debugger. It's supposed to be one that also uses lldb, but I'm not sure how to reference that adapter in my `setup_handlers`.  Any assistance or tips would be really helpful.

**Comment by jayp0521** [comment]
hello,

`lldb` doesn't seem to be officially supported. will tackle this sometime this week. will probably opt for `cpptools` unless you have any objections: https://github.com/williamboman/mason.nvim/blob/main/lua/mason-registry/cpptools/init.lua

**Comment by jayp0521** [comment]
nvim-dap shows 3 ways of doing it. unsure what the best is, https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#ccrust-via-vscode-cpptools

**Comment by jayp0521** [comment]
https://github.com/jayp0521/mason-nvim-dap.nvim/pulls

**Comment by jayp0521** [comment]
https://github.com/jayp0521/mason-nvim-dap.nvim/pull/15

**Comment by chewbakartik** [comment]
Thanks for this. I must admit that I'm struggling with configuring and setting up dap just in general, both with and without this plugin. The how to do it hasn't clicked for me yet.

This is what I have in my config, maybe you can help point me in the right direction for figuring out what's wrong:
```
local mason_nvim_dap_status_ok, mv_dap = pcall(require, "mason-nvim-dap")
if not mason_nvim_dap_status_ok then
  return
end

mv_dap.setup({
  ensure_installed = { "python", "node2", "chrome", "php", "js", "rust", "bash", "javadbg", "javatest" },
  automatic_setup = true,
})
```
When I toggle a breakpoint 
`<cmd>lua require'dap'.toggle_breakpoint()<cr>' 
and then run with continue 
`<cmd>lua require'dap'.continue()<cr>` 

I get the message `No configuration found for `rust`. You need to add configs to `dap.configurations.rust` (See `:h dap-configuration`)

**Comment by jayp0521** [comment]
> Thanks for this. I must admit that I'm struggling with configuring and setting up dap just in general, both with and without this plugin. The how to do it hasn't clicked for me yet.
> 
> This is what I have in my config, maybe you can help point me in the right direction for figuring out what's wrong:
> ```
> local mason_nvim_dap_status_ok, mv_dap = pcall(require, "mason-nvim-dap")
> if not mason_nvim_dap_status_ok then
>   return
> end
> 
> mv_dap.setup({
>   ensure_installed = { "python", "node2", "chrome", "php", "js", "rust", "bash", "javadbg", "javatest" },
>   automatic_setup = true,
> })
> ```
> When I toggle a breakpoint 
> `<cmd>lua require'dap'.toggle_breakpoint()<cr>' 
> and then run with continue 
> `<cmd>lua require'dap'.continue()<cr>` 
> 
> I get the message `No configuration found for `rust`. You need to add configs to `dap.configurations.rust` (See `:h dap-configuration`)

https://github.com/jayp0521/mason-nvim-dap.nvim#setup-handlers-usage

It seems like you are missing this. Please read the Note in the section.
