### ISSUE TITLE
Please add other adapters

### ISSUE THREAD

**Issue by nikitalocalhost** [jayp0521/mason-nvim-dap.nvim#5]
Or at least add option to pass unknown adapters from setup_handlers to dap

- [x]  bash
- [x] codelldb
- [x] java-debug-adapter
- [x] java-test
- [x] js-debug-adapter
- [x] mockdebug
- [x] pupeet-editor-services
- [x] elixir-ls

**Comment by jinzhongjia** [comment]
I took a look at [jayp0521](https://github.com/jayp0521)'s homepage, he hasn't made any code submissions for a week, if you need these appapters urgently, you can check out my [fork](https://github.com/jinzhongjia/mason-nvim-dap.nvim)

**Comment by jinzhongjia** [comment]
And I have initiated a pr, now waiting to merge
